config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do
    resources :horses, :shallow => true
  end
  resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horse.rb
class Horse < ApplicationRecord
  scope :recent, -> { order("created_at DESC").limit(5) }
  belongs_to :user

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :horses

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  include ApplicationHelper

  def new
    @user = User.find(session[:user_id])
    @horse = Horse.new
  end

  def edit
    if current_user
      @horse = Horse.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.find(session[:user_id])
    @horse = @user.horses.new(horse_params)

    if @horse.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @horse = Horse.find(params[:id])
  end

  def update
    @horse = Horse.find(params[:id])
    @user = @horse.user

    if @horse.update(horse_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @horse = Horse.find(params[:id])
    @user = @horse.user
    @horse.destroy

    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.json { head :no_content }
      format.js { render :layout => false }
    end

    # redirect_to user_path(@user)
  end

private

  def horse_params
    params.require(:horse).permit(:name, :breed, :age)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper

  def new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @horses = Horse.recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      nil
    end
  end

  def authorize
    redirect_to new_session_path unless current_user
  end
end

app/views/horses/edit.html.erb
<%= form_for @horse, url: horse_path(@horse), method: :patch do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :breed %>
  <%= f.text_field :breed %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit %>
  
<% end %>

app/views/horses/new.html.erb
<h1>New Horse</h1>

<%= form_for([@user, @user.horses.build]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :breed %>
  <%= f.text_field :breed %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Horses</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to "#{current_user.username}", user_path(current_user) %> | <%= link_to 'Logout', session_path(current_user), method: :delete %>
    <% else %>
      <%= link_to 'Login', new_session_path %> | <%= link_to 'Signup', new_user_path %>
    <% end %>
     | <%= link_to 'Home', root_path %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>:
  <%= f.text_field :username %>

  <%= f.label :email %>:
  <%= f.text_field :email %>

  <%= f.label :password %>:
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>

<h3>Your horses</h3>
<div class="new-horse">
  <%= link_to 'Add New Horse', new_user_horse_path(@user) %>
</div>

<% @user.horses.each do |horse| %>
  <div class="horse-container">
    <h4><%= horse.name %></h4>
    <p><%= horse.breed %></p>
    <p>Age <%= horse.age %></p>
    <%= link_to 'Edit', edit_horse_path(horse) %> | <%= link_to 'Delete', horse_path(horse), method: :delete, :class => "delete_horse", :remote => true %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1 class="big">Meet the Herd</h1>

<% if current_user %>
  <%= link_to 'Add New Horse', new_user_horse_path(current_user) %>
<% end %>

<% @horses.each do |horse| %>
  <h4><%= horse.name %></h4>
  <p><%= horse.breed %></p>
  <p>Age <%= horse.age %></p>
  <p>Owned by <%= horse.user.username %></p>
<% end %>